services:
# -----------------------------------------------------------------------
    mariadb:
      build: ./requirements/mariadb
      image: image_mariadb
      container_name: mariadb_container
      init: true
      restart: unless-stopped
      environment:
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      volumes:
        - mariadb:/var/lib/mysql
      networks:
        - docker-network
#-----------------------------------------------------------------------
    nginx:
      build: ./requirements/nginx
      image: image_nginx
      container_name: nginx_container
      init: true
      ports:
        - "443:443"
      restart: unless-stopped
      depends_on:
        - wordpress
      volumes:
        - wordpress:/var/www/wordpress
      networks:
        - docker-network
# -----------------------------------------------------------------------
    wordpress:
      build: ./requirements/wordpress
      image: image_wordpress
      container_name: wordpress_container
      init: true
      restart: unless-stopped
      environment:
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
        - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
        - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
        - WORDPRESS_USER=${WORDPRESS_USER}
        - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      depends_on:
        - mariadb
        - redis
      volumes:
        - wordpress:/var/www/wordpress
      networks:
        - docker-network
# -----------------------------------------------------------------------
    static-site:
      build: ./requirements/bonus/static_site
      image: image_static_site
      container_name: static_site_container
      init: true
      ports:
        - "80:80"
      restart: unless-stopped
      networks:
        - docker-network
# -----------------------------------------------------------------------
    portainer:
      build: ./requirements/bonus/portainer
      image: image_portainer
      container_name: portainer_container
      init: true
      ports:
        - "9000:9000"
      restart: unless-stopped
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer:/data
      networks:
        - docker-network
# -----------------------------------------------------------------------
    ftp:
      build: ./requirements/bonus/ftp
      image: image_ftp
      container_name: ftp_container
      init: true
      ports:
        - "21:21"
        - "21000-21010:21000-21010"
      restart: unless-stopped
      depends_on:
        - wordpress
      environment:
        - FTP_USER=${FTP_USER}
        - FTP_PASSWORD=${FTP_PASSWORD}
      volumes:
        - wordpress:/var/www/wordpress
      networks:
        - docker-network
# -----------------------------------------------------------------------
    adminer:
      build: ./requirements/bonus/adminer
      image: image_adminer
      container_name: adminer_container
      init: true
      ports:
        - "8080:8080"
      restart: unless-stopped
      networks:
        - docker-network
# -----------------------------------------------------------------------
    redis:
      build: requirements/bonus/redis
      image: image_redis
      container_name: redis_container
      init: true
      restart: unless-stopped
      networks:
        - docker-network
# -----------------------------------------------------------------------
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  portainer:
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/portainer
# -----------------------------------------------------------------------
networks:
  docker-network:
    driver: bridge
