services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: image_nginx
    container_name: nginx_container
    ports:
      - "443:443"
    restart: unless-stopped
  
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: image_mariadb
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}